"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Choice = { productId: string; variantId: string | null; label: string };
type BundleValue = { id?: string; name: string; status: string; items: Array<{ productId: string | null; variantId: string | null; quantity: number }>; listings: Array<{ marketCode: string; cost: number; individualTotal: number; price: number }> };

export default function BundleForm({ choices, initial }: { choices: Choice[]; initial?: BundleValue }) {
  const router = useRouter(); const [value, setValue] = useState<BundleValue>(initial ?? { name: "", status: "DRAFT", items: [], listings: [] }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const toggleMarket = (marketCode: string) => setValue((current) => ({ ...current, listings: current.listings.some((listing) => listing.marketCode === marketCode) ? current.listings.filter((listing) => listing.marketCode !== marketCode) : [...current.listings, { marketCode, cost: 0, individualTotal: 0, price: 0 }] }));
  async function save() { setSaving(true); setError(""); const response = await fetch(initial?.id ? `/api/bundles/${initial.id}` : "/api/bundles", { method: initial?.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(value) }); const result = await response.json(); setSaving(false); if (!response.ok) return setError(result.error || "Could not save bundle"); router.push("/bundles"); router.refresh(); }
  return <div className="bg-white border rounded p-5 space-y-5"><label className="block">Name<input className="border rounded p-2 w-full" value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })}/></label><label className="block">Status<select className="border rounded p-2 w-full" value={value.status} onChange={(event) => setValue({ ...value, status: event.target.value })}>{["DRAFT","ACTIVE","HIDDEN","ARCHIVED"].map((status)=><option key={status}>{status}</option>)}</select></label><section><h2 className="font-bold mb-2">Components</h2><select className="border rounded p-2 w-full" defaultValue="" onChange={(event)=>{const choice=choices[Number(event.target.value)];if(choice)setValue({...value,items:[...value.items,{productId:choice.productId,variantId:choice.variantId,quantity:1}]});event.target.value=""}}><option value="">Add product / variant…</option>{choices.map((choice,index)=><option value={index} key={`${choice.productId}-${choice.variantId}`}>{choice.label}</option>)}</select>{value.items.map((item,index)=><div className="flex gap-2 items-center mt-2" key={`${item.productId}-${item.variantId}-${index}`}><span className="flex-1">{choices.find((choice)=>choice.productId===item.productId&&choice.variantId===item.variantId)?.label}</span><input className="border rounded p-2 w-24" type="number" min="1" value={item.quantity} onChange={(event)=>{const items=[...value.items];items[index]={...item,quantity:Number(event.target.value)};setValue({...value,items})}}/><button type="button" onClick={()=>setValue({...value,items:value.items.filter((_,i)=>i!==index)})}>Remove</button></div>)}</section><section><h2 className="font-bold mb-2">Market listings</h2><div className="flex gap-2">{["EGYPT","MOROCCO"].map((code)=><button type="button" className={`border rounded px-3 py-2 ${value.listings.some((listing)=>listing.marketCode===code)?"bg-[#c6a227]":""}`} onClick={()=>toggleMarket(code)} key={code}>{code}</button>)}</div>{value.listings.map((listing,index)=><div className="border rounded p-3 mt-3 grid md:grid-cols-4 gap-2" key={listing.marketCode}><b>{listing.marketCode} · {listing.marketCode==="EGYPT"?"EGP":"MAD"}</b>{(["cost","individualTotal","price"] as const).map((field)=><label key={field}>{field}<input className="border rounded p-2 w-full" type="number" min="0" step="0.01" value={listing[field]} onChange={(event)=>{const listings=[...value.listings];listings[index]={...listing,[field]:Number(event.target.value)};setValue({...value,listings})}}/></label>)}</div>)}</section>{error&&<p className="text-red-600">{error}</p>}<button disabled={saving} onClick={save} className="bg-[#c6a227] rounded px-4 py-2">{saving?"Saving…":"Save Bundle"}</button></div>;
}
