import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";
import { searchPublicCatalogue, publicSuggestions } from "../lib/public-search";
import { quotePublicCart } from "../lib/public-cart-quote";
const db = new PrismaClient();
async function main() {
  if (!process.env.DATABASE_URL?.includes("/mata3_catalogue_v12b_test")) throw new Error("Isolated v1.2B test database required");
  const eg = await db.market.create({ data: { code: "EGYPT", name: "Egypt", currency: "EGP" } });
  const ma = await db.market.create({ data: { code: "MOROCCO", name: "Morocco", currency: "MAD" } });
  const department = await db.department.findUniqueOrThrow({ where: { name: "Gaming" } });
  const gaming = await db.category.create({ data: { name: "Gaming Controllers", departmentId: department.id } });
  const accessories = await db.category.create({ data: { name: "Accessories", departmentId: department.id } });
  const controller = await db.product.create({ data: { sku: "PRIVATE-CTRL", nameEn: "Controller", nameAr: "يد تحكم", descriptionEn: "Game controller", status: "ACTIVE", publicSlug: "controller", categoryId: gaming.id, internalNotes: "SECRET NOTE" } });
  const black = await db.productVariant.create({ data: { productId: controller.id, sku: "PRIVATE-BLACK", color: "Black", size: "Standard" } });
  const white = await db.productVariant.create({ data: { productId: controller.id, sku: "PRIVATE-WHITE", color: "White", size: "Standard" } });
  const blackEg = await db.marketListing.create({ data: { productId: controller.id, variantId: black.id, marketId: eg.id, cost: 450, price: 649, webPublicationStatus: "PUBLISHED" } });
  const whiteEg = await db.marketListing.create({ data: { productId: controller.id, variantId: white.id, marketId: eg.id, cost: 480, price: 699, webPublicationStatus: "PUBLISHED" } });
  const blackMa = await db.marketListing.create({ data: { productId: controller.id, variantId: black.id, marketId: ma.id, cost: 520, price: 799, webPublicationStatus: "PUBLISHED" } });
  await db.inventory.create({ data: { listingId: blackEg.id, marketId: eg.id, currentStock: 4 } });
  await db.inventory.create({ data: { listingId: whiteEg.id, marketId: eg.id, currentStock: 2 } });
  await db.inventory.create({ data: { listingId: blackMa.id, marketId: ma.id, currentStock: 2 } });
  const dock = await db.product.create({ data: { sku: "PRIVATE-DOCK", nameEn: "Charging Dock", nameAr: "قاعدة شحن", status: "ACTIVE", publicSlug: "charging-dock", categoryId: gaming.id } });
  const dockEg = await db.marketListing.create({ data: { productId: dock.id, marketId: eg.id, cost: 200, price: 399, webPublicationStatus: "PUBLISHED" } });
  await db.inventory.create({ data: { listingId: dockEg.id, marketId: eg.id, currentStock: 3 } });
  const mouse = await db.product.create({ data: { sku: "PRIVATE-MOUSE", nameEn: "Mouse", nameAr: "فأرة", status: "ACTIVE", publicSlug: "mouse", categoryId: accessories.id } });
  const mouseEg = await db.marketListing.create({ data: { productId: mouse.id, marketId: eg.id, cost: 80, price: 149, webPublicationStatus: "PUBLISHED" } });
  await db.inventory.create({ data: { listingId: mouseEg.id, marketId: eg.id, currentStock: 5 } });
  const draft = await db.product.create({ data: { sku: "PRIVATE-DRAFT", nameEn: "Controller Draft", nameAr: "مسودة", status: "ACTIVE", publicSlug: "controller-draft" } });
  const draftListing = await db.marketListing.create({ data: { productId: draft.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "DRAFT" } });
  const hidden = await db.product.create({ data: { sku: "PRIVATE-HIDDEN", nameEn: "Controller Hidden", nameAr: "مخفي", status: "ACTIVE", publicSlug: "controller-hidden" } });
  const hiddenListing = await db.marketListing.create({ data: { productId: hidden.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "HIDDEN" } });
  const inactive = await db.product.create({ data: { sku: "PRIVATE-INACTIVE", nameEn: "Controller Inactive", nameAr: "غير نشط", status: "DRAFT", publicSlug: "controller-inactive" } });
  const inactiveListing = await db.marketListing.create({ data: { productId: inactive.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "PUBLISHED" } });
  const bundle = await db.bundle.create({ data: { name: "Controller Bundle", status: "ACTIVE", publicSlug: "controller-bundle" } });
  const bundleEg = await db.bundleMarketListing.create({ data: { bundleId: bundle.id, marketId: eg.id, cost: 700, individualTotal: 1697, price: 949, webPublicationStatus: "PUBLISHED" } });
  await db.bundleItem.create({ data: { bundleId: bundle.id, variantId: black.id, quantity: 1 } });
  await db.bundleItem.create({ data: { bundleId: bundle.id, variantId: black.id, quantity: 1 } });
  await db.bundleItem.create({ data: { bundleId: bundle.id, productId: dock.id, quantity: 1 } });

  const search = (overrides: Partial<Parameters<typeof searchPublicCatalogue>[0]> = {}) => searchPublicCatalogue({ market: "EGYPT", q: "", page: 1, pageSize: 24, sort: "name_asc", ...overrides });
  const all = await search();
  assert.equal(all?.total, 4);
  assert.deepEqual((await search({ q: "Controller" }))?.items.map(item => item.slug), ["charging-dock", "controller", "controller-bundle"]);
  assert.equal((await search({ market: "MOROCCO", q: "Dock" }))?.total, 0);
  assert.equal((await search({ q: "Draft" }))?.total, 0);
  assert.equal((await search({ q: "Hidden" }))?.total, 0);
  assert.equal((await search({ q: "Inactive" }))?.total, 0);
  assert.deepEqual((await search({ pageSize: 2, page: 2, sort: "price_asc" }))?.items.map(item => item.slug), ["controller", "controller-bundle"]);
  assert.deepEqual((await search({ sort: "price_desc" }))?.items.map(item => item.slug), ["controller-bundle", "controller", "charging-dock", "mouse"]);
  assert.deepEqual((await search({ category: gaming.publicKey }))?.items.map(item => item.slug), ["charging-dock", "controller"]);
  assert.deepEqual((await search({ color: "Black" }))?.items.map(item => item.slug), ["controller"]);
  assert.deepEqual((await search({ size: "Standard" }))?.items.map(item => item.slug), ["controller"]);
  assert.deepEqual((await search({ maxPriceMinor: 40000, sort: "price_asc" }))?.items.map(item => item.slug), ["mouse", "charging-dock"]);
  assert.deepEqual(all?.facets.categories.map(item => [item.name, item.count]), [["Accessories", 1], ["Gaming Controllers", 2]]);
  assert.deepEqual(all?.facets.colors.map(item => item.value), ["Black", "White"]);
  assert.deepEqual(all?.facets.sizes.map(item => item.value), ["Standard"]);
  assert.deepEqual(all?.facets.price, { minAmountMinor: 14900, maxAmountMinor: 94900, currency: "EGP" });
  const suggestions = await publicSuggestions("EGYPT", "Control");
  assert.deepEqual(suggestions?.products.map(item => item.slug), ["controller"]);
  assert.deepEqual(suggestions?.categories.map(item => item.key), [gaming.publicKey]);
  assert.equal((await publicSuggestions("MOROCCO", "Dock"))?.products.length, 0);
  const searchText = JSON.stringify(all) + JSON.stringify(suggestions);
  for (const forbidden of ["PRIVATE", "SECRET NOTE", "cost", "supplier", "profit", "margin", "currentStock", "inventorySource", "availableQuantity"]) assert.equal(searchText.includes(forbidden), false, forbidden);

  const before = { inventory: await db.inventory.findMany({ select: { id: true, currentStock: true, reservedStock: true } }), movements: await db.inventoryMovement.count(), sales: await db.sale.count() };
  const quote = async (market: string, lines: Parameters<typeof quotePublicCart>[1]) => quotePublicCart(market, lines);
  const good = await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 1, observedUnitAmountMinor: 64900 }]);
  assert.equal(good?.canProceed, true);
  assert.equal(good?.itemsSubtotal.amountMinor, 64900);
  assert.equal(good?.currency, "EGP");
  assert.equal(good?.reservation, false);
  const morocco = await quote("MOROCCO", [{ key: blackMa.publicOfferId, quantity: 1 }]);
  assert.equal(morocco?.itemsSubtotal.amountMinor, 79900);
  assert.equal(morocco?.currency, "MAD");
  assert.deepEqual((await quote("MOROCCO", [{ key: blackEg.publicOfferId, quantity: 1 }]))?.lines[0].codes, ["WRONG_MARKET"]);
  assert.deepEqual((await quote("EGYPT", [{ key: draftListing.publicOfferId, quantity: 1 }]))?.lines[0].codes, ["NOT_PUBLIC"]);
  assert.deepEqual((await quote("EGYPT", [{ key: hiddenListing.publicOfferId, quantity: 1 }]))?.lines[0].codes, ["NOT_PUBLIC"]);
  assert.deepEqual((await quote("EGYPT", [{ key: inactiveListing.publicOfferId, quantity: 1 }]))?.lines[0].codes, ["NOT_PUBLIC"]);
  assert.deepEqual((await quote("EGYPT", [{ key: "not-a-key", quantity: 1 }]))?.lines[0].codes, ["INVALID_KEY"]);
  assert.deepEqual((await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 0 }]))?.lines[0].codes, ["INVALID_QUANTITY"]);
  assert.deepEqual((await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 100 }]))?.lines[0].codes, ["INVALID_QUANTITY"]);
  await db.marketListing.update({ where: { id: whiteEg.id }, data: { available: false } });
  assert.deepEqual((await quote("EGYPT", [{ key: whiteEg.publicOfferId, quantity: 1 }]))?.lines[0].codes, ["UNAVAILABLE"]);
  const duplicate = await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 3 }, { key: blackEg.publicOfferId, quantity: 2 }]);
  assert.equal(duplicate?.canProceed, false);
  assert.ok(duplicate?.lines.every(line => line.codes.includes("INSUFFICIENT_STOCK")));
  const bundleConflict = await quote("EGYPT", [{ key: bundleEg.publicOfferId, quantity: 2 }, { key: blackEg.publicOfferId, quantity: 1 }]);
  assert.equal(bundleConflict?.canProceed, false);
  assert.ok(bundleConflict?.lines[0].codes.includes("BUNDLE_UNAVAILABLE"));
  assert.ok(bundleConflict?.lines[1].codes.includes("INSUFFICIENT_STOCK"));
  assert.equal((await quote("EGYPT", [{ key: bundleEg.publicOfferId, quantity: 1 }]))?.canProceed, true);
  await db.marketListing.update({ where: { id: blackEg.id }, data: { price: 679 } });
  const changed = await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 1, observedUnitAmountMinor: 64900 }]);
  assert.equal(changed?.canProceed, false);
  assert.deepEqual(changed?.lines[0].codes, ["PRICE_CHANGED"]);
  assert.equal(changed?.lines[0].unitPrice?.amountMinor, 67900);
  assert.equal((await quote("EGYPT", [{ key: blackEg.publicOfferId, quantity: 1, observedUnitAmountMinor: 67900 }]))?.canProceed, true);
  const quoteText = JSON.stringify(changed) + JSON.stringify(bundleConflict);
  for (const forbidden of ["PRIVATE", "SECRET NOTE", "cost", "supplier", "profit", "margin", "currentStock", "inventorySource", "availableQuantity"]) assert.equal(quoteText.includes(forbidden), false, forbidden);
  const after = { inventory: await db.inventory.findMany({ select: { id: true, currentStock: true, reservedStock: true } }), movements: await db.inventoryMovement.count(), sales: await db.sale.count() };
  assert.deepEqual(after, before);
  console.log("v1.2B search and cart quote checks passed");
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => db.$disconnect());
