import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";
import { getPublicMarkets, getPublicCategories, getPublicProducts, getPublicProductBySlug, getPublicBundles, getPublicBundleBySlug } from "../lib/public-catalogue";
const db = new PrismaClient();
async function main() {
if (!process.env.DATABASE_URL?.includes("/mata3_catalogue_v12a_test")) throw new Error("Test database required");
const eg = await db.market.create({ data: { code: "EGYPT", name: "Egypt", currency: "EGP" } });
const ma = await db.market.create({ data: { code: "MOROCCO", name: "Morocco", currency: "MAD" } });
const department = await db.department.findUniqueOrThrow({ where: { name: "Gaming" } });
const category = await db.category.create({ data: { name: "Controllers", departmentId: department.id } });
const product = await db.product.create({ data: { sku: "PRIVATE-SKU", nameEn: "Controller", nameAr: "يد تحكم", status: "ACTIVE", publicSlug: "controller", categoryId: category.id } });
const variant = await db.productVariant.create({ data: { productId: product.id, sku: "PRIVATE-VARIANT", color: "Black" } });
const egListing = await db.marketListing.create({ data: { productId: product.id, variantId: variant.id, marketId: eg.id, price: "649.00", cost: "450.00", webPublicationStatus: "PUBLISHED" } });
const maListing = await db.marketListing.create({ data: { productId: product.id, variantId: variant.id, marketId: ma.id, price: "799.00", cost: "520.00", webPublicationStatus: "PUBLISHED" } });
await db.inventory.create({ data: { listingId: egListing.id, marketId: eg.id, currentStock: 4 } });
await db.inventory.create({ data: { listingId: maListing.id, marketId: ma.id, currentStock: 2 } });
await db.productImage.create({ data: { productId: product.id, url: "/internal-recognition.jpg", alt: "Private" } });
const draftMedia = await db.webProductMedia.create({ data: { productId: product.id, type: "IMAGE", storageKey: "web-media/draft.jpg", url: "/draft.jpg", altText: "Draft", sortOrder: 0 } });
const cover = await db.webProductMedia.create({ data: { productId: product.id, type: "IMAGE", storageKey: "web-media/cover.jpg", url: "/cover.jpg", altText: "Cover", isCover: true, sortOrder: 5, publicationStatus: "PUBLISHED" } });
await db.webProductMedia.create({ data: { productId: product.id, type: "IMAGE", storageKey: "web-media/support.jpg", url: "/support.jpg", altText: "Support", sortOrder: 1, publicationStatus: "PUBLISHED" } });
await db.webProductMedia.create({ data: { variantId: variant.id, type: "VIDEO", storageKey: "web-media/video.mp4", url: "/video.mp4", altText: "Video", publicationStatus: "PUBLISHED" } });
const draft = await db.product.create({ data: { sku: "DRAFT", nameEn: "Draft", nameAr: "مسودة", status: "ACTIVE", publicSlug: "draft" } });
await db.marketListing.create({ data: { productId: draft.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "DRAFT" } });
const hidden = await db.product.create({ data: { sku: "HIDDEN", nameEn: "Hidden", nameAr: "مخفي", status: "ACTIVE", publicSlug: "hidden" } });
await db.marketListing.create({ data: { productId: hidden.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "HIDDEN" } });
const inactive = await db.product.create({ data: { sku: "INACTIVE", nameEn: "Inactive", nameAr: "غير نشط", status: "DRAFT", publicSlug: "inactive" } });
await db.marketListing.create({ data: { productId: inactive.id, marketId: eg.id, cost: 1, price: 2, webPublicationStatus: "PUBLISHED" } });
const nonphysical = await db.product.create({ data: { sku: "ON-DEMAND", nameEn: "On demand", nameAr: "حسب الطلب", status: "ACTIVE", publicSlug: "on-demand" } });
await db.marketListing.create({ data: { productId: nonphysical.id, marketId: eg.id, cost: 1, price: 10, inventoryType: "ON_DEMAND", webPublicationStatus: "PUBLISHED" } });
const bundle = await db.bundle.create({ data: { name: "Controller bundle", status: "ACTIVE", publicSlug: "controller-bundle" } });
const bundleListing = await db.bundleMarketListing.create({ data: { bundleId: bundle.id, marketId: eg.id, cost: 450, individualTotal: 649, price: 599 } });
await db.bundleItem.create({ data: { bundleId: bundle.id, variantId: variant.id, quantity: 2 } });
try {
  const markets = await getPublicMarkets();
  assert.deepEqual(markets.items.map(item => item.currency).sort(), ["EGP", "MAD"]);
  const categories = await getPublicCategories("EGYPT");
  assert.equal(categories?.items[0].key, category.publicKey);
  const egPage = await getPublicProducts("EGYPT", 1, 1);
  assert.equal(egPage?.total, 2);
  assert.equal(egPage?.items.length, 1);
  assert.equal((await getPublicProducts("EGYPT", 2, 1))?.items.length, 1);
  const detail = await getPublicProductBySlug("EGYPT", "controller");
  assert.equal(detail?.offers[0].offerId, egListing.publicOfferId);
  assert.equal(detail?.offers[0].price.amountMinor, 64900);
  assert.equal(detail?.offers[0].price.currency, "EGP");
  assert.equal(detail?.offers[0].purchasable, true);
  assert.deepEqual(detail?.media.map(item => item.url), ["/cover.jpg", "/support.jpg"]);
  assert.equal(detail?.offers[0].media[0].url, "/video.mp4");
  const serialized = JSON.stringify(detail);
  for (const forbidden of ["PRIVATE-SKU", "PRIVATE-VARIANT", "internal-recognition", "cost", "supplier", "profit", "margin", "currentStock", "availableQuantity", "listingId", "inventorySource"]) assert.equal(serialized.includes(forbidden), false, forbidden);
  const maDetail = await getPublicProductBySlug("MOROCCO", "controller");
  assert.equal(maDetail?.offers[0].price.amountMinor, 79900);
  assert.equal(maDetail?.offers[0].price.currency, "MAD");
  assert.equal(await getPublicProductBySlug("EGYPT", "draft"), null);
  assert.equal(await getPublicProductBySlug("EGYPT", "hidden"), null);
  assert.equal(await getPublicProductBySlug("EGYPT", "inactive"), null);
  assert.equal(await getPublicProductBySlug("MOROCCO", "on-demand"), null);
  assert.equal((await getPublicProductBySlug("EGYPT", "on-demand"))?.offers[0].purchasable, false);
  assert.equal((await getPublicBundles("EGYPT"))?.total, 0);
  await db.bundleMarketListing.update({ where: { id: bundleListing.id }, data: { webPublicationStatus: "PUBLISHED" } });
  assert.equal((await getPublicBundleBySlug("EGYPT", "controller-bundle"))?.purchasable, true);
  const privateBundle = await db.bundle.create({ data: { name: "Private bundle", status: "ACTIVE", publicSlug: "private-bundle" } });
  await db.bundleMarketListing.create({ data: { bundleId: privateBundle.id, marketId: eg.id, cost: 1, individualTotal: 2, price: 2, webPublicationStatus: "PUBLISHED" } });
  await db.bundleItem.create({ data: { bundleId: privateBundle.id, productId: draft.id, quantity: 1 } });
  assert.equal(await getPublicBundleBySlug("EGYPT", "private-bundle"), null);
  assert.equal((await getPublicBundles("EGYPT"))?.total, 1);
  assert.equal(await getPublicBundleBySlug("MOROCCO", "controller-bundle"), null);
  await db.inventory.update({ where: { listingId: egListing.id }, data: { reservedStock: 3 } });
  assert.equal((await getPublicBundleBySlug("EGYPT", "controller-bundle"))?.purchasable, false);
  assert.equal((await getPublicProductBySlug("EGYPT", "controller"))?.offers[0].purchasable, true);
  await db.webProductMedia.update({ where: { id: cover.id }, data: { publicationStatus: "HIDDEN" } });
  assert.deepEqual((await getPublicProductBySlug("EGYPT", "controller"))?.media.map(item => item.url), ["/support.jpg"]);
  assert.equal(draftMedia.publicationStatus, "DRAFT");
  await db.marketListing.update({ where: { id: egListing.id }, data: { available: false } });
  assert.equal((await getPublicProductBySlug("EGYPT", "controller"))?.offers[0].purchasable, false);
  let duplicateRejected = false;
  try { await db.marketListing.create({ data: { productId: draft.id, marketId: eg.id, cost: 1, price: 2 } }); } catch { duplicateRejected = true; }
  assert.equal(duplicateRejected, true);
  console.log("public catalogue contract checks passed");
} finally { await db.$disconnect(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
